jobs:
  merge_changesets_pr:
    name: Merge Changesets PR
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        name: Merge the Changesets PR if it is old enough
        run: |
          pr_json=$(gh pr list --head changeset-release/main --state open --json createdAt,number --limit 1)

          if [ "$(echo "$pr_json" | jq length)" = "0" ]; then
            echo "No open Changesets PR found."
            exit 0
          fi

          pr_number=$(echo "$pr_json" | jq -r '.[0].number')
          created_at=$(echo "$pr_json" | jq -r '.[0].createdAt')
          created_at_timestamp=$(date --date="$created_at" +%s)
          three_days_ago_timestamp=$(date --date="3 days ago" +%s)

          if [ "$created_at_timestamp" -gt "$three_days_ago_timestamp" ]; then
            echo "Changesets PR #$pr_number is less than 3 days old."
            exit 0
          fi

          gh pr merge "$pr_number" --auto --squash

name: Merge Changesets PR

on:
  schedule:
    - cron: "0 14 * * 1"
  workflow_dispatch: ~
