jobs:
  post_release:
    name: Post Release
    runs-on: ubuntu-latest
    steps:
      - uses: apexskier/github-release-commenter@e7813a9625eabd79a875b4bc4046cfcae377ab34 # v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            :tada: This has been released in **{release_tag}** :tada:

            The release is available on [GitHub releases]({release_link}).

            Cheers! 📦🚀

name: Post Release

on:
  release:
    types:
      - published

permissions:
  issues: write
  pull-requests: write
