concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pack:
    if: needs.select_mode.outputs.mode == 'publish'
    name: Pack
    needs: select_mode
    outputs:
      pack-dir-artifact-id: ${{ steps.pack.outputs.pack-dir-artifact-id }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - id: pack
        uses: changesets/action/pack@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          publish-plan-artifact-id: ${{ needs.select_mode.outputs.publish-plan-artifact-id }}

  publish:
    name: Publish
    needs: pack
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/prepare
      - uses: changesets/action/publish@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          pack-dir-artifact-id: ${{ needs.pack.outputs.pack-dir-artifact-id }}

  select_mode:
    name: Select Mode
    outputs:
      mode: ${{ steps.select_mode.outputs.mode }}
      publish-plan-artifact-id: ${{ steps.select_mode.outputs.publish-plan-artifact-id }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/prepare
      - id: select_mode
        uses: changesets/action/select-mode@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2

  version:
    if: needs.select_mode.outputs.mode == 'version'
    name: Version
    needs: select_mode
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/prepare
      - uses: changesets/action/version@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          commit-message: "chore: version packages"
          github-token: ${{ secrets.ACCESS_TOKEN }}
          pr-title: "chore: version packages"

name: Release

on:
  push:
    branches:
      - main

permissions: {}
